//fetch.java
import java.io.*;
import java.sql.*;
import jakarta.servlet.*;
import jakarta.servlet.http.*;

public class fetch extends HttpServlet
{
   public void doGet(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException
    {
       res.setContentType("text/html");
       PrintWriter pw=res.getWriter();
       String eid=req.getParameter("eid");//101
       try{
       Class.forName("oracle.jdbc.OracleDriver");
       Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345");
       PreparedStatement pst=con.prepareStatement("select * from tueemp where eid=?");
       pst.setString(1,eid);
        ResultSet rs=pst.executeQuery();
        if(rs.next())
         {
		pw.println("<h3>Eid "+rs.getString(1));
		pw.println("<br>Name "+rs.getString("name"));
		pw.println("<br>Degn "+rs.getString(3));
		pw.println("<br>Salary "+rs.getInt(4));
         }
          else
            {
               pw.println("<h1>Invalid empid");
             }
          con.close();
          }
          catch(Exception e){}
         }
}


/*
      ResultSet ->it a predefined class used to point the output table
       generated by executeQuery(). For row wise traversal we use next() and for columnwise traversal we use column index or name
   eid  name   degn  sal
    101  ---     ---   ---

*/




       